### PR TITLE
Widget Updates

### PR DESCRIPTION
**Pull request by David-Yarnell**
Added some widgets and updated current widgets to WAB Developer Edition 1.3.

### CODE REVIEW

**Comment by torrin47** [comment]
Thanks!

**Comment by trmluu** [comment]
Hello hello,

Sadly, i am no longer w EPA. Please take me off the distribution list. :/

Happy new year!

Truc

On Monday, January 4, 2016, Torrin Hultgren notifications@github.com
wrote:

> Thanks!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/USEPA/Public_Web_AppBuilder/pull/2#issuecomment-168760946
> .

## 

Truc-Mai Luu
trmluu@gmail.com
240-422-6908

**Comment by trmluu** [comment]
Hello hello,

Sadly, i am no longer w EPA. Please take me off the distribution list

On Monday, January 4, 2016, Torrin Hultgren <notifications@github.com
<javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:

> Thanks!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/USEPA/Public_Web_AppBuilder/pull/2#issuecomment-168760946
> .

## 

Truc-Mai Luu
trmluu@gmail.com
240-422-6908

**Comment by jankrysa** [comment]
Thanks for adding the updates!

**Pull request merged**
